### ISSUE TITLE
Force 'X-Api-Version: 1' until this plugin gets updated with the v2 changes

### ISSUE THREAD

**Issue by stefanoverna** [static-dev/spike-datocms#12]
See https://www.datocms.com/changelog/cma-v2/. Uploads should now be fetched from a different endpoint (`client.uploads.all`). In the meantime, you can explicitly pass a 'X-Api-Version: 1' to get back the old behaviour:

https://github.com/static-dev/spike-datocms/blob/master/lib/index.js#L10

```js
    this.client = new SiteClient(opts.token, { 'X-Api-Version': '1' })
```

datocms-client package should be >=0.5.7

**Comment by stefanoverna** [comment]
In alternative, in the "package.json" datocms-client v0.4.6 should be required, which is the latest that uses the v1 API.

**Comment by mcrider** [comment]
Can confirm that this fixes what is otherwise a very broken integration with Dato and this Spike plugin.

**Comment by jescalan** [comment]
Got it, just updated and released a patch!
